PAYEES_CODES = (
    ('000', 'Approval', ''),
    ('103', 'Format Error', ''),
    ('130', 'Invalid Format', ''),
    ('178', 'Original Request not Found', ''),
    ('158', 'Invalid processing code', ''),
    ('161', 'Withdrawal limit exceeded', ''),
    ('191', 'Destination not available', ''),
    ('194', 'Duplicate transaction', ''),
    ('196', 'System error', ''),
    ('201', 'Contact Card Issuer', ''),
    ('205', 'External decline', ''),
    ('251', 'Insufficient fund', ''),
    ('281', 'Wrong customer information', ''),
    ('338', 'PIN tries limit exceeded', ''),
    ('355', 'Invalid PIN', ''),
    ('375', 'PIN Tries Limit Reached', ''),
    ('362', 'Encryption error', ''),
    ('389', 'Invalid terminal ID', ''),
    ('412', 'Invalid transaction', ''),
    ('413', 'Merchant limit exceeded', ''),
    ('467', 'Invalid amount', ''),
    ('514', 'Invalid track 2', ''),
    ('536', 'Restricted card', ''),
    ('541', 'Lost card', ''),
    ('543', 'Stolen card', ''),
    ('550', 'Closed card', ''),
    ('552', 'Declared card', ''),
    ('554', 'Expired card', ''),
    ('600', 'Invalid client ID', ''),
    ('601', 'Invalid card number format', ''),
    ('602', 'Invalid expiry date format', ''),
    ('603', 'Format Error', ''),
    ('604', 'Invalid Currency Code', ''),
    ('605', 'Invalid Account Format', ''),
    ('606', 'Invalid System Trace Audit Number Format', ''),
    ('607', 'Invalid Personal Payment Information Format', ''),
    ('608', 'Invalid Payee Identification', ''),
    ('609', 'Invalid phone number format', ''),
    ('610', 'Invalid voucher number format', ''),
    ('611', 'Invalid transaction date format', ''),
    ('615', 'Invalid service Id', ''),
    ('616', 'Invalid original transaction system trace audit number format', ''),
    ('617', 'MCS Time Out', ''),
    ('618', 'This service cannot be reversed', ''),
    ('619', 'Invalid Terminal Id Format', ''),
    ('620', 'Invalid PIN Format', ''),
    ('621', 'Invalid Amount Format', ''),
    ('622', 'Invalid Cash Back Amount Format', ''),
    ('632', 'MCS Invalid Cash Out Transaction due to Invalid voucher length', ''),
    ('696', 'MCS System Error', ''),
)
